[tool.poetry]
name = "bills-analyzer"
version = "0.1.0"
description = ""
authors = ["DidgetyTech <32182119+DidgetyTech@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pypdf = "^3.16"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
